config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'                       #rootにするとURL/へアクセスした時にトップページが表示されるようになる
  get '/signup', to: 'users#new'
  
  #ログイン
  get '/login', to: 'sessions#new'              #新しいセッションのページ 
  post '/login', to: 'sessions#create'          #新しいセッションの作成 
  delete '/logout', to: 'sessions#destroy'

  resources :bases

  resources :users do
    collection { post :import }                 #:idでurlを識別する必要がない場合はcollectionで設定
    member do                                   #:idがつくURIを生成する
      get 'search', to: 'users#search' 
      get 'edit_basic_info'                     #基本情報編集
      patch 'update_basic_info'                 #基本情報更新

      get 'attendances/edit_one_month'          #勤怠編集画面
      patch 'attendances/update_one_month'      #勤怠編集画面登録

      get 'attendances/edit_one_month_apply'    #1ヶ月勤怠申請
      patch 'attendances/update_one_month_apply'#1ヶ月勤怠申請

      get 'show_verify'                         #上長勤怠確認
      
      get 'commuting_employee'                  #出勤中社員一覧
      
      get :export, defaults: { format: 'csv' }
    end
    resources :attendances, only: :update do
      member do
        get 'edit_request_change'               #勤怠変更申請モーダル
        patch 'update_request_change'           #勤怠変更申請承認
        
        get 'edit_request_overtime'             #残業申請モーダル
        patch 'update_request_overtime'         #残業申請登録
        
        get 'edit_overtime_approval'            #残業申請通知モーダル
        patch 'update_overtime_approval'        #残業承認登録
        
        get 'edit_one_month_approval'           #1ヶ月勤怠申請通知モーダル
        patch 'update_one_month_approval'       #1ヶ月勤怠承認
        
        get 'edit_fix_log'                      #勤怠修正ログ (承認済)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  require 'csv'
  has_many :attendances, dependent: :destroy
  attribute :scheduled_end_time, :time
  attr_accessor :remember_token #記憶トークンとユーザーをremember_tokenという仮想の属性を作成します。
  before_save { self.email = email.downcase } #selfはユーザーオブジェクトを指す
  
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
            format: { with: VALID_EMAIL_REGEX }, #VALID_EMAIL_REGEX定数に正規表現を定義し、formatバリデーションを追加し、
            uniqueness: true                     #withで正規表現を指定することでメールアドレスのフォーマットを制限しています。
  validates :affiliation, length: { in: 2..50 }, allow_blank: true#値が空の場合はバリデーションを実行しない  #validates :employee_number, presence: true, uniqueness: true
  validates :basic_work_time, presence: true
  validates :work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
                      #presence: trueを用いることでそのカラムの値が存在するかどうかをチェックできる。
  # 渡された文字列のハッシュ化を行う。
  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end                                    
    BCrypt::Password.create(string, cost: cost) #文字列をハッシュ化してBCrypt::Passwordインスタンスを返す。
  end                                           #ハッシュ化したい文字列stringとコストパラメータcostをBCrypt::Password.createメソッドに渡すと、渡した文字列をハッシュ化してくれる。
                                                #コストパラメータを高く設定すると、よりセキュリティの高いハッシュ値を生成するらしい。
  
  #ランダムな文字列（記憶トークン）を生成するUserクラスのクラスメゾットuser.digestを作る
  #Rubyの標準ライブラリのSecureRandomモジュールのurlsafe_base64メソッドを使う
  def User.new_token
    SecureRandom.urlsafe_base64
  end 
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
        #selfを記述することで仮想のremember_token属性にUser.new_tokenで生成した
        #「ハッシュ化されたトークン情報」を代入しています。
        #selfがないと、単純にremember_tokenというローカル変数が作成されてしまいます。
        
        #update_attributesと違い（よく見ると末尾にsがあるかないかの違いがあります）
        #こちらはバリデーションを素通りさせます。
        #今回はユーザーのパスワードなどにアクセス出来ないため、
        #このメソッドを用いてバリデーションを素通りさせる必要がありました。
        
  #トークンがダイジェストと一致すればtrueを返します。      
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end                    #データベース                #cookiesに保存されている。

  #ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  #ユーザー検索
  def self.search(search)
    return User.all unless search
    User.where(['name LIKE ?', "%#{search}%"])
  end

  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      user = find_by(id: row["id"]) || new # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user.attributes = row.to_hash.slice(*updatable_attributes)  # CSVからデータを取得し、設定する
      user.save!(validate: false)
    end 
  end
  
 
  # ユーザー一覧　ユーザー編集　更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid",
    "basic_work_time", "designated_work_start_time", "designated_work_end_time",
    "superior", "admin", "password"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  before_action :set_user, only: %i[show edit update update_basic_info destroy commuting_employee show_verify]
  before_action :logged_in_user, only: %i[index edit update destroy edit_basic_info update_basic_info]
  before_action :correct_user, only: %i[show edit update] 
  before_action :admin_user, only: %i[index destroy edit_basic_info update_basic_info commuting_employee]
  before_action :admin_access, only: %i[show]
  before_action :set_one_month, only: %i[show show_verify]

  def index
    @users = User.order(created_at: :asc).paginate(page: params[:page], per_page: 17)
    @users = @users.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
  end
 
  def show
    @attendance = @user.attendances.find_by(worked_on: Date.current.beginning_of_month)
    @superiors = User.where(superior: true).where.not(id: @user.id)#一般ユーザーでなく上長を取得する。
    @worked_sum = @attendances.where.not(started_at: nil).count#出勤がない日以外を取得し、合計を出す。
    @overtime_sum = Attendance.where(request_overtime_superior: @user.name, request_overtime_status: "申請中").count#残業申請を上長に申請している日の合計を出す。
    @change_sum = Attendance.where(request_change_superior: @user.name, request_change_status: "申請中").count#勤怠変更時間を上長に申請している日の合計を出す。
    @one_month_sum = Attendance.where(one_month_apply_superior: @user.name, one_month_apply_status: "申請中").count#1ヶ月の勤怠申請している月を取得する
    
    # 勤怠一覧CSVファイルエクスポート
    respond_to do |format| #respont_to (HTML、JSON、XMLなど）に対して異なるレスポンスを生成する際に使用。
      format.html #HTML形式のレスポンスを生成。
      format.csv do |csv| #CSV形式のリクエストに対するレスポンスを定義
        export_csv(@attendances) #メソッドによってCSVデータが生成され、それがレスポンスとして返される仕組み。
      end
    end
  end  

  def show_verify
    @worked_sum = @attendances.where.not(started_at: nil).count
    @overtime_sum = Attendance.where(request_overtime_superior: @user.name, request_overtime_status: "申請中").count
    @change_sum = Attendance.where(request_change_superior: @user.name, request_change_status: "申請中").count
    @one_month_sum = Attendance.where(one_month_apply_superior: @user.name, one_month_apply_status: "申請中").count
  end  

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)#直接にparams[:カラムの値]とならないのは、Railsがストロンパラメータという値を安全に受け取る仕組みを採用しているから。
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
  end
  
  #アカウント情報の更新（設定）
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to users_url
    else
      flash[:danger] = "ユーザー情報を更新出来ませんでした。"
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    if @user.update(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報は更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  #社員一覧名簿インポート
  def import
    if User.import(params[:file])
      flash[:success] = "CSVファイルのインポートに成功しました。"
    elsif params[:file].blank?
      flash[:danger] =  "CSVファイルを選択して下さい。"
    else
      flash[:danger] = "CSVファイルのインポートに失敗しました。"
    end
    redirect_to users_url
  end


  def commuting_employee
    @users = User.all.order(:id)
  end


  def search
     #Viewのformで取得したパラメータをモデルに渡す
    @users = User.search(params[:search])
  end

  
  private #Web経由で外部のユーザーが知る必要は無いため、次に記すようにRubyのprivateキーワードを用いて
          #外部からは使用できないようにする。


  #Strong Parameters          
  def user_params 
    params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid,
                                :password, :password_confirmation, :basic_work_time,
                                :designated_work_start_time, :designated_work_end_time)
  end

  def basic_info_params
    params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid,
                                :password, :password_confirmation, :basic_work_time,
                                :designated_work_start_time, :designated_work_end_time)
  end 
  
  
  #勤怠一覧CSVファイルエクスポート
  def export_csv(attendances)
    csv_data = CSV.generate do |csv|
      header = %w(日付 出勤時間 退勤時間)
      #CSVファイルに、header という配列の要素を追加している。
      csv << header # << 「シフト演算子」または「追加演算子」
       
      attendances.each do |day|
        #表の行に入る値を定義
        values = [ 
          l(day.worked_on, format: :long),
          if day.after_started_at.present? && (day.request_change_status == "承認").present?
            l(day.after_started_at, format: :time)
          else
            nil
          end,
          if day.after_finished_at.present? && (day.request_change_status == "承認").present?
            l(day.after_finished_at, format: :time)
          else
            nil
          end
          ]
          csv << values
      end
    end
    send_data(csv_data, filename: "勤怠一覧.csv")
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 勤怠基本情報を指定のフォーマットで返します。
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_admin.html.erb
<% provide(:btn_text, '更新') %>
<% provide(:class_text, 'user--edit') %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :employee_number, class: "form-control" %>

  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>
  
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>
 

app/views/users/_user.index.html.erb
<% provide(:class_text, 'user--edit') %>

<%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :employee_number, class: "form-control" %>

  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>
  
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>

  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>

  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>
  
  <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>
 

app/views/users/commuting_employee.html.erb
<% provide(:title, '出勤中社員一覧') %>

<h1>出勤中社員一覧</h1>
<div class="row"><!-- 横並びにしたいコンテンツがある時使用 -->
  <div class= "col col-md-12">
    <table class= "table table-bordered" id = "table">
      <thead>
        <tr>
          <th>社員番号</th>
          <th>名前</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <% user.attendances.where(worked_on: Date.current). each do |day| %>
            <% if day.started_at.present? && day.finished_at.blank? %>
              <tr>
                <td><%= user.employee_number %></td>
                <td><%= user.name %></td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div> 
</div>

app/views/users/edit.html.erb
<% provide(:title,"Edit") %>
<h1>アカウント情報の更新</h1>

<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <% if current_user.admin? %>
      <%= render 'admin' %>
    <% else %>
      <%= render 'form' %>
    <% end %>
  </div>
</div>
  

app/views/users/edit_basic_info.html.erb
<h1>基本情報の更新</h1>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<% provide(:btn_text, '更新') %>

  <h1>ユーザー一覧</h1>
  
  <div class="input-group">
    <%= form_with(url: import_users_path, method: :post, multipart: true) do |f| %>
      <%= f.file_field :file, accept: '.csv' %>
      <%= f.submit "CSVをインポート", class: "btn btn-primary" %>
    <% end %>
  </div>

  
  <div class= "row" id= "search">
    <div class= "col-lg-3">
      <p>ユーザー名検索</p>
      <%= form_with(url: users_path(current_user), method: :get, local: true) do |f| %>
        <div class="input-group"> 
          <%= f.text_field :search, value: params[:search], class: "form-control", placeholder: 'キーワードを入力...' %>
            <span class= "input-group-btn" >
              <%= f.submit '検索', class: "btn btn-primary" %>
            </span>
        </div>
      <% end %>
    </div>
  </div>
  
  <div class="col-md-11 col-offset-1">
    <% @users.each do |user| %>
      <% unless user.admin? %>
        <%= user.name %><br>
          <%= link_to "削除", user, method: :delete, 
            data: { confirm: "削除してよろしいですか？" },
            class: "btn btn-primary" %>
        
        <div class="panel-group">
          <div class="panel panel-default">
            <div class="panel-heading">
              <div class="panel-title">
                <button data-toggle="collapse" data-target="#collapse<%= user.id %>" type="button" class = "btn btn-primary">編集</button>
              </div>                                        
            </div>
            <div id="collapse<%= user.id %>" class="panel-collapse collapse">
              <div class="panel-body">
                <%= render 'user.index', locals: {user: @user = User.find_by(id: user.id) } %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>  

app/views/users/show.html.erb
  <% provide(:title, @user.name) %>
  <div>
    <table class = "table table-bordered table-condensed user-table">
      <tr>
        <td>
          <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
          <%= l(@first_day, format: :middle) %>時間管理表
          <%= link_to "→", user_path(date: @first_day.next_month),class: "btn btn-primary" %>
        </td>
        <td>
          指定勤務開始時間&nbsp;&nbsp;<%= format_basic_info(@user.designated_work_start_time) %><br>
          指定勤務終了時間<%= format_basic_info(@user.designated_work_end_time) %>
        </td>
        <td colspan = "3">基本時間<%= format_basic_info(@user.basic_work_time) %></td>
        <td>初日&nbsp;&nbsp;<%= l(@first_day, format: :short) %></td>
      </tr>
      
      <tr>
        <td>所属&nbsp;<%= @user.affiliation.present? ? @user.affiliation: "未所属" %></td>
        <td>氏名&nbsp;&nbsp;<%= @user.name %></td>
        <td>コード</td> 
        <td><%=@user.employee_number %></td>
        <td>出勤日数&nbsp;&nbsp;<%= @worked_sum %>日</td>
        <td>締め <%= l(@last_day, format: :short) %></td>
      </tr>
    </table>
  </div>
  
  <div class = "superior-link">
    <% if @user.superior? && current_user?(@user) %>
      <% if @one_month_sum > 0 %>
        <%= link_to "【所属長承認申請のお知らせ】", edit_one_month_approval_user_attendance_path(@user), remote: true, class: "btn-superior" %>
        <span style= "border: solid 2px red; color: red;"> 
        <%= link_to "#{@one_month_sum}件の通知があります。", edit_one_month_approval_user_attendance_path(@user), remote: true, class: "btn-superior" %></span><br>
      <% else %>
        <%= "【所属長承認申請のお知らせ】" %><br>
      <% end %>
      <% if @change_sum > 0 %>
        <%= link_to "【勤怠変更申請のお知らせ】", edit_request_change_user_attendance_path(@user), remote: true, class: "btn-superior" %>
        <span style= "border: solid 2px red; color: red;">
        <%= link_to "#{@change_sum}件の通知があります。", edit_request_change_user_attendance_path(@user), remote: true, class: "btn-superior" %></span><br>
      <% else %>
        <%= "【勤怠変更申請のお知らせ】" %><br>
      <% end %>
      <% if @overtime_sum > 0 %>
        <%= link_to "【残業申請のお知らせ】", edit_overtime_approval_user_attendance_path(@user), remote: true, class: "btn-superior" %>
        <span style= "border: solid 2px red; color: red;">
        <%= link_to "#{@overtime_sum}件の通知があります。", edit_overtime_approval_user_attendance_path(@user), remote: true, class: "btn-superior" %></span><br>
      <% else %>
        <%= "【残業申請のお知らせ】" %><br>
      <% end %>
    <% end %>
  </div>
  
  <div class="btn-attendance">
    <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
    <%= link_to "CSV出力", user_path(format: :csv), class: "btn btn-primary" %>
    <%= link_to "勤怠修正ログ（承認済）", edit_fix_log_user_attendance_path(@user), class: "btn btn-primary" %>
  </div>
  
  <div>
    <table class = "table table-bordered table-condensed table-striped" id = "table">
      <thead>
        <tr>
          <th rowspan = "3">残業申請</th>
          <th rowspan = "3">日付</th>
          <th rowspan = "3">曜日</th>
          <th colspan = "7">【実績】</th>
          <th colspan = "6">所定外勤務</th>
        </tr>
        <tr>
          <th rowspan = "2"></th>
          <th colspan = "2">出社</th>
          <th colspan = "2">退社</th>
          <th rowspan = "2">在社時間</th>
          <th rowspan = "2">備考</th>
          <th colspan = "2">終了予定時間</th>
          <th rowspan = "2">時間外時間</th>
          <th rowspan = "2">業務処理内容</th>
          <th rowspan = "2">指示者確認㊞</th>
        </tr>
        <tr>
          <th>時</th>
          <th>分</th>
          <th>時</th>
          <th>分</th>
          <th>時</th>
          <th>分</th>
        </tr>
      </thead>
  
      <tbody>
        <% @attendances.each do |day| %>
          <tr>
            <td><%= link_to "残業申請", edit_request_overtime_user_attendance_path(@user, day), remote: true, class: "btn btn-primary" %></td><!--remote:true ajax通信で画面遷移することなく、データを保存してページの一部だけ更新することが出来る。-->
            <td><%= l(day.worked_on, format: :short) %></td>
            <td class='<%= "wday#{day.worked_on.wday}" %>'><%= $days_of_the_week[day.worked_on.wday] %></td>
            <td width = 100>
              <% if btn_text = attendance_state(day) %>
                <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
              <% end %>
            </td>
            <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
            <td><%= l(day.started_at, format: :minute) if day.started_at.present? %></td><!--minuteをja.yml/ formats:にminute: "%M"を追加-->
            <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
            <td><%= l(day.finished_at, format: :minute) if day.finished_at.present? %></td>
            <td>
              <% if day.started_at.present? && day.finished_at.present? %>
                <%= working_times(day.started_at, day.finished_at) %>
                <% @total_working_times = @total_working_times.to_f + working_times(day.started_at, day.finished_at).to_f %>
              <% end %>
            </td>
            <td><%= day.note %></td>
            <td><%= day.scheduled_end_time.strftime("%H") if day.scheduled_end_time.present? %></td>
            <td><%= day.scheduled_end_time.strftime("%M") if day.scheduled_end_time.present? %></td>
            <td>
              <% if day.scheduled_end_time.present? %>
                <%= working_overtimes(day.scheduled_end_time, @user.designated_work_end_time, day.overtime_next_day) %>
              <% end %>
            </td>
            <td><%= day.work_description %></td>
            <td>
              <% if day.request_overtime_status == "申請中" %>
                <%= "#{day.request_overtime_superior}へ残業#{day.request_overtime_status}" %><br>
              <% elsif day.request_overtime_status == "承認" || day.request_overtime_status == "否認" %>
                <%= "#{day.request_overtime_superior}より残業#{day.request_overtime_status}" %><br>
              <% elsif day.request_overtime_status == "なし" %>
                <%= "#{day.request_overtime_superior}より残業承認なし" %><br>
              <% end %>
              <% if day.request_change_status == "申請中" %>
                <%= "#{day.request_change_superior}へ勤怠変更#{day.request_change_status}" %><br>
              <% elsif day.request_change_status == "承認" || day.request_change_status == "否認" %>
                <%= "#{day.request_change_superior}より勤怠変更#{day.request_change_status}" %><br>
              <% elsif day.request_change_status == "なし" %>
                <%= "#{day.request_change_superior}より勤怠変更承認なし" %><br>
              <% end %>
            </td>  
          </tr>
        <% end %>
      </tbody>
      
      <tfoot>
        <!--rowspan:縦結合、colspan:横結合-->
        <tr>
          <td rowspan = "2"></td>
          <td colspan = "2">累計日数</td>
          <td colspan = "5">総合勤務時間</td>
          <td colspan = "2">累計在社時間</td>
          <td colspan = "3" rowspan = "2"></td>
          <td rowspan = "2">
          <td rowspan = "2">
            <div class="form-group">
              <% if current_user?(@user) %>
                <%= form_with(model: @attendance, url: attendances_update_one_month_apply_user_path(@user), local: true, method: :patch) do |f| %>
                  <%= f.hidden_field :one_month_apply_status, value: "申請中" %>
                  <%= f.hidden_field :apply, value: @first_day %>
                  <!-- フォームが送信された時に"申請中"、日付情報を送られる -->
                  <% if @attendance.one_month_apply_status == "申請中" %>
                    <%= "#{@attendance.one_month_apply_superior}へ申請中" %>
                  <% elsif @attendance.one_month_approval_status == "否認" %>
                    <%= "#{@attendance.one_month_apply_superior}より否認" %>
                  <% elsif @attendance.one_month_approval_status == "承認" %>
                    <%= "#{@attendance.one_month_apply_superior}より承認" %>
                  <% elsif @attendance.one_month_approval_status == "なし" %>
                    <%= "#{@attendance.one_month_apply_superior}より承認なし" %>
                  <% else %>
                    <%= "所属長承認 未" %>
                  <% end %>
                  <br>
                  <%= f.collection_select :one_month_apply_superior, @superiors, :name, :name, { include_blank: "上長を選択して下さい" } %>
                  <!--セレクトボックスに最初の選択肢として "上長を選択して下さい" を表示-->
                  <%= f.submit "申請", class: "btn btn-primary btn-block" %>
                <% end %>            
              <% end %>
            </div>
          </td>
        </tr>
        <tr>
          <td colspan = "2"><%= @attendances.count %></td>
           <td colspan = "5"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td> 
          <td colspan = "2"><%= format("%.2f", @total_working_times.to_f) %></td>
        </tr>
      </tfoot>
    </table>
  </div>
  
  <!--モーダルウインドウ表示-->
  <div id="edit-request-overtime" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
  <div id= "edit-overtime-approval" class= "modal fade" tabindex= "-1" role= "dialog" aria-hidden= "true"></div>
  <div id= "edit-one-month-approval" class= "modal fade" tabindex= "-1" role= "dialog" aria-hidden= "true"></div>
  <div id= "edit-request-change" class= "modal fade" tabindex= "-1" role= "dialog" aria-hidden= "true"></div>

app/views/users/top.html.erb
<% provide(:title,'Top') %>
<div class = "center jumbotron">
  <h1>勤怠システム</h1>
  <%= link_to "ログイン", login_path, class: "btn btn-lg btn-primary" %> 
  <p>アカウントの作成は<%= link_to "こちら", signup_path %>から</p>
</div>