config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'                       #rootにするとURL/へアクセスした時にトップページが表示されるようになる
  get '/signup', to: 'users#new'
  
  #ログイン
  get '/login', to: 'sessions#new'              #新しいセッションのページ 
  post '/login', to: 'sessions#create'          #新しいセッションの作成 
  delete '/logout', to: 'sessions#destroy'

  resources :bases

  resources :users do
    collection { post :import }                 #:idでurlを識別する必要がない場合はcollectionで設定
    member do                                   #:idがつくURIを生成する
      get 'search', to: 'users#search' 
      get 'edit_basic_info'                     #基本情報編集
      patch 'update_basic_info'                 #基本情報更新

      get 'attendances/edit_one_month'          #勤怠編集画面
      patch 'attendances/update_one_month'      #勤怠編集画面登録

      get 'attendances/edit_one_month_apply'    #1ヶ月勤怠申請
      patch 'attendances/update_one_month_apply'#1ヶ月勤怠申請

      get 'show_verify'                         #上長勤怠確認
      
      get 'commuting_employee'                  #出勤中社員一覧
      
      get :export, defaults: { format: 'csv' }
    end
    resources :attendances, only: :update do
      member do
        get 'edit_request_change'               #勤怠変更申請モーダル
        patch 'update_request_change'           #勤怠変更申請承認
        
        get 'edit_request_overtime'             #残業申請モーダル
        patch 'update_request_overtime'         #残業申請登録
        
        get 'edit_overtime_approval'            #残業申請通知モーダル
        patch 'update_overtime_approval'        #残業承認登録
        
        get 'edit_one_month_approval'           #1ヶ月勤怠申請通知モーダル
        patch 'update_one_month_approval'       #1ヶ月勤怠承認
        
        get 'edit_fix_log'                      #勤怠修正ログ (承認済)
      end
    end
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  validates :worked_on, presence: true
  validates :note, length: {maximum: 50}

  #出勤時間が存在しない場合、退勤時間は無効
  #validate :finished_at_is_invalid_without_a_started_at
  
  #退勤時間が存在しない場合、出勤時間は無効
  #validate :started_at_is_invalid_without_a_finished_at
  
  #出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid
  
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, 'が必要です') if started_at.blank? && finished_at.present?
  end
  
  def started_at_is_invalid_without_a_finished_at
    errors.add(:finished_at, 'が必要です') if finished_at.blank? && started_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, 'より早い退勤時間は無効です') if started_at > finished_at
    end
  end
end 

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  protect_from_forgery

  before_action :set_user, only: %i[edit_one_month update_one_month edit_request_change update_request_change  update_one_month_apply edit_overtime_approval]
  before_action :set_user_id, only: %i[update edit_request_change update_request_change edit_request_overtime update_request_overtime edit_overtime_approval update_overtime_approval edit_one_month_approval update_one_month_approval edit_fix_log]
  before_action :set_attendance_id, only: %i[update edit_request_overtime update_request_overtime edit_overtime_approval]
  before_action :logged_in_user, only: %i[update edit_one_month edit_fix_log]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :admin_access, only: %i[edit_one_month update_one_month edit_fix_log]
  before_action :correct_user, only: %i[edit_fix_log]
  before_action :set_one_month, only: %i[edit_one_month edit_fix_log update_one_month_apply]

  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直して下さい。"


  # 出退勤打刻
  def update
    attendance = Attendance.find(params[:id])
      if attendance.started_at.nil?
        if attendance.update(started_at: Time.current.change(sec: 0))
          flash[:info] = "おはようございます！"
        else
          flash[:danger] = UPDATE_ERROR_MSG
        end
      else attendance.finished_at.nil?
        if attendance.update(finished_at: Time.current.change(sec: 0))
          flash[:info] = "お疲れ様でした。"
        else
          flash[:danger] = UPDATE_ERROR_MSG
        end
      end
      redirect_to @user
  end

  def edit_one_month
    @superiors = User.where(superior: true).where.not(id: @user.id)
  end


# 勤怠編集更新
  def update_one_month
    request_count = 0
    ActiveRecord::Base.transaction do
      attendances_params.each do |id, item|
        if item[:request_change_superior].present?
          if item[:after_started_at].present? && item[:after_finished_at].blank?
            flash[:danger] = "退社時間を入力してください。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date])
            return
          elsif item[:after_started_at].blank? && item[:after_finished_at].present?
            flash[:danger] = "出勤時間を入力してください。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date])
            return
          elsif item[:after_started_at].blank? && item[:after_finished_at].blank?
            flash[:danger] = "出勤時間と退勤時間を入力してください。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date])
            return
          elsif item[:next_day] == "0" && item[:after_started_at].present? && item[:after_finished_at].present? && item[:after_started_at] > item[:after_finished_at]
            flash[:danger] = "退社時間が出勤時間よりも早いです。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date])
            return
          elsif item[:note].blank?
            flash[:danger] = "備考欄に理由を入力してください。"
            redirect_to attendances_edit_one_month_user_url(date: params[:date])
            return
          end
          attendance = Attendance.find(id)
          item[:request_change_status] = "申請中" #更新後に勤怠画面（指示者確認欄に表示）
          request_count += 1
          attendance.update!(item)
        end
      end
      if request_count > 0
        flash[:success] = "勤怠申請を#{request_count}件送りました。"
        redirect_to user_url(date: params[:date]) and return
      else
        flash[:danger] = "未入力箇所があります。"	
        redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "勤怠情報に不備があります。再度確認してください。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
  end


  #勤怠変更申請お知らせモーダル
  def edit_request_change
    @attendances = Attendance.where(request_change_superior: @user.name, request_change_status: "申請中").order(:worked_on).group_by(&:user_id)
  end
  #検索結果をworked_onカラムの値でソートし、user_idでグループ化
  # &はブロックの省略形式
  
  # 勤怠変更申請モーダル承認
  def update_request_change
    request_count = 0
    request_change_params.each do |id, item|
      attendance = Attendance.find(id)
      if item[:change_check] == "1"
        if item[:request_change_status] == "承認"
          if attendance.before_started_at.blank? && attendance.before_finished_at.blank?
            attendance.before_started_at = attendance.after_started_at
            attendance.before_finished_at = attendance.after_finished_at
          end
          attendance.started_at = attendance.after_started_at
          attendance.finished_at = attendance.after_finished_at
        elsif item[:request_change_status] == "なし"
          item[:request_change_status] = "なし" #更新後に勤怠画面（指示者確認欄に表示）
          item[:note] = nil
          attendance.after_started_at = nil if attendance.after_started_at.present?
          attendance.after_finished_at = nil if attendance.after_finished_at.present?
        elsif item[:request_change_status] == "申請中"
          flash[:danger] = "指示者確認㊞を申請中以外で選択してください。"
          redirect_to user_url(@user)
          return
        end 
      elsif item[:change_check] == "0"
        if item[:request_change_status] == "申請中"
          flash[:danger] = "指示者確認㊞を申請中以外を選択し変更欄にチェックを入れてください。"
          redirect_to user_url(@user)
          return
        else
          flash[:danger] = "変更欄にチェックを入れてください。"
          redirect_to user_url(@user)
          return
        end
      end
      attendance.update(item)
      request_count += 1
    end
    if request_count > 0
      flash[:success] = "勤怠変更の申請結果を#{request_count}件送信しました."
      redirect_to user_url(@user)
    end
  end

  #残業申請モーダル
  def edit_request_overtime
    @superiors = User.where(superior: true).where.not(id: @user.id)
    @attendances = Attendance.where(request_overtime_superior: @user.name, request_overtime_status: "申請中").order(:worked_on).group_by(&:user_id)
  end

  #残業申請モーダル更新
  def update_request_overtime
    if request_overtime_params[:request_overtime_superior].blank? || request_overtime_params[:scheduled_end_time].blank? || request_overtime_params[:work_description].blank? || request_overtime_params[:overtime_next_day].blank?
      flash[:danger] = "未入力欄があります."
      redirect_to user_url(@user)
      return
    elsif @attendance.started_at.nil? && @attendance.finished_at.nil?
      flash[:danger] = "無勤では残業申請できません。"
      redirect_to user_url(@user)
      return
    else
      if @attendance.update(request_overtime_params)
        params[:attendance][:request_overtime_status] = "申請中"
        flash[:success] = "#{@user.name}さんの残業を申請しました."
      else
        flash[:danger] = "残業の申請に不備があります。再度確認してください."
      end
    end
    redirect_to user_url(@user) and return
  end


  #残業申請通知モーダル
  def edit_overtime_approval
    @attendances = Attendance.where(request_overtime_superior: @user.name, request_overtime_status: "申請中").order(:worked_on).group_by(&:user_id)
  end

  #残業申請通知モーダル承認更新
  def update_overtime_approval
    request_count = 0
    overtime_approval_params.each do |id, item|
      attendance = Attendance.find(id)
      if item[:overtime_check] == "1"
        if item[:request_overtime_status] == "承認"
          if item[:designated_work_end_time].present? && item[:scheduled_end_time] > item[:designated_work_end_time]
            flash[:danger] = "申請の終了時間が指示の終了時間を超えています。"
            redirect_to user_url(@user)
            return
          end
        elsif item[:request_overtime_status] == "否認"
          if item[:designated_work_end_time].present? && item[:scheduled_end_time] < item[:designated_work_end_time]
            flash[:danger] = "申請の終了時間が指示の終了時間より早いです。"
            redirect_to user_url(@user)
            return
          end
        elsif item[:request_overtime_status] == "申請中"
          flash[:danger] = "指示者確認欄㊞が申請中になっています。"
          redirect_to user_url(@user)
          return
        elsif item[:request_overtime_status] == "なし"
          item[:request_overtime_status] = "なし" # 更新後に勤怠画面（指示者確認欄に表示）
          item[:scheduled_end_time] = nil if item[:scheduled_end_time].present?
          item[:designated_work_end_time] = nil if item[:designated_work_end_time].present?
          item[:work_description] = nil if item[:work_description].present?
          item[:overtime_next_day] = nil if item[:overtime_next_day].present?
        end
      elsif item[:overtime_check] == "0"
        if item[:request_overtime_status] == "申請中"
          flash[:danger] = "変更チェックを入れ、指示者確認欄を申請中以外で選択してください。"
          redirect_to user_url(@user)
          return
        elsif 
          flash[:danger] = "変更チェックを入れてください。"
          redirect_to user_url(@user)
          return
        end
      end
      request_count += 1
      attendance.update(item)
    end
    if request_count > 0
      flash[:success] = "残業申請結果を#{request_count}件送信しました。"
    else
      flash[:danger] = "更新する残業申請がありません。"
    end
    redirect_to user_url(@user)
  end

  
  def edit_one_month_apply
    @attendances = Attendance.where(one_month_apply_superior: @user.name, one_month_apply_status: "申請中")
  end

  
  #1ヶ月勤怠申請
  def update_one_month_apply
    @attendance = @user.attendances.find_by(worked_on: @first_day)      
    if one_month_apply_params[:one_month_apply_superior].present?
      flash[:success] = "所属長承認申請が送信されました。"
    elsif one_month_apply_params[:one_month_apply_superior].blank?
      one_month_apply_params[:one_month_apply_superior] = "上長を選択して下さい"
      flash[:danger] = "所属長を選択して下さい。"
      redirect_to user_url(@user)
      return
    end
      @attendance.update(one_month_apply_params)
      one_month_apply_params[:one_month_apply_status] = "申請中"
      redirect_to user_url(@user)
      return
  end

  #1ヶ月勤怠申請通知モーダル
  def edit_one_month_approval
    @attendances = Attendance.where(one_month_apply_superior: @user.name, one_month_apply_status: "申請中").order(worked_on: :asc).group_by(&:user_id)
  end

  #1ヶ月勤怠申請承認
  def update_one_month_approval
   #debugger
    request_count = 0

app/helpers/attendances_helper.rb
module AttendancesHelper  #ViewをDRY（Don’t Repeat Yourself）に作る

  def attendance_state(attendance)
      # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    #どれにも当てはまらなかった場合はfalseを返します。
    return false
  end

  # 出勤時間と退勤時間を受け取り、実際の労働時間を秒単位で在社時間を計算して返します。
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end
  
  #時間外時間
  def working_overtimes(scheduled_end_time, designated_work_end_time, overtime_next_day)
    if overtime_next_day == true
      format("%.2f", (scheduled_end_time.hour - designated_work_end_time.hour) + (scheduled_end_time.min - designated_work_end_time.min) / 60.0 + 24)
    else
      format("%.2f", (scheduled_end_time.hour - designated_work_end_time.hour) + (scheduled_end_time.min - designated_work_end_time.min) / 60.0)
    end
  end

  
   #不正な値があるか確認する
  def attendances_invalid?
    attendances = true
    attendances_params.each do |id, item|
      if item[:started_at].blank? && item[:finished_at].blank?
        next
      elsif item[:started_at].blank? || item[:finished_at].blank?
        attendances = false
        break
      end
    end
    return attendances
  end
end

app/views/attendances/_edit_one_month_approval.html.erb
<% provide(:btn_text, '変更を送信する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row"><!-- 横並びにしたいコンテンツがある時使用 -->
        <div class= "col-md-12">
         <%= form_with(model: @user, url: update_one_month_approval_user_attendance_path(@user), method: :patch, local: true) do |f| %>
           <!--ユーザーごとの勤怠情報を処理。ユーザーID（id）をキーとして、勤怠情報のコレクション（attendances）を値として持つ-->
          <% @attendances.each do |id, attendance| %>
            <% user = User.find(id) %>
            <h1 class="modal-title"><%= "【#{user.name}からの1ヶ月分勤怠申請】" %></h1>
            <table class="table table-bordered" id="table">
              <thead>
                <tr>
                  <th>月</th>
                  <th>指示者確認㊞</th>
                  <th>変更</th>
                  <th>勤怠を確認する</th>
                </tr>
              </thead>
              <tbody>
                <!-- 各ユーザーの勤怠情報 -->
                <% attendance.each do |day| %>
                  <%= f.fields_for "attendances[]", day do |a| %>
                    <tr>
                      <td><%= day.worked_on.month %>月</td>
                      <td><%= a.select :one_month_approval_status, ["なし", "申請中", "承認", "否認"] %></td>
                      <td><%= a.check_box :approval_check %></td>
                      <td><%= link_to "確認", show_verify_user_path(user, date: day.worked_on.beginning_of_month), class: "btn btn-primary" %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
            <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block" %>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_overtime_approval.html.erb
<% provide(:btn_text, '変更を送信する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row"><!-- 横並びにしたいコンテンツがある時使用 -->
        <div class= "col-md-12">
          <%= form_with(model: @user, url: update_overtime_approval_user_attendance_path(@user), local: true, method: :patch) do |f| %>
            <% @attendances.each do |id, attendances| %>
              <% user = User.find(id) %>
              <h1 class="modal-title"><%= "【#{user.name}からの残業申請】"%></h1>
                <table class= "table table-bordered table-condensed table-hover" id= "table-attendances">
                  <thead>
                    <tr>
                      <th rowspan="2">日付</th>
                      <th rowspan="2">曜日</th>
                      <th colspan="2">終了予定時間</th>
                      <th colspan="2">指定勤務終了時間</th>
                      <th rowspan="2">時間外時間</th>
                      <th rowspan="2">業務処理内容</th>
                      <th rowspan="2">指示者確認㊞</th>
                      <th rowspan="2">変更</th>
                      <th rowspan="2">勤怠を確認する</th>
                    </tr>
                    <tr>
                      <th>時</th>
                      <th>分</th>
                      <th>時</th>
                      <th>分</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% attendances.each do |day| %>
                      <%= f.fields_for "attendances[]", day do |a| %>
                        <tr>
                          <td><%= l(day.worked_on, format: :short) if day.worked_on.present? %></td>
                          <td class= '<%= "wday#{day.worked_on.wday}" %>'><%= $days_of_the_week[day.worked_on.wday] %></td>
                          <td><%= l(day.scheduled_end_time, format: :hour) if day.scheduled_end_time.present? %></td>
                          <td><%= l(day.scheduled_end_time, format: :minute) if day.scheduled_end_time.present? %></td>
                          <td><%= l(user.designated_work_end_time, format: :hour) if user.designated_work_end_time.present? %></td>
                          <td><%= l(user.designated_work_end_time, format: :minute) if user.designated_work_end_time.present? %></td>
                          <td>
                            <% if day.scheduled_end_time.present? %>
                              <%= working_overtimes(day.scheduled_end_time, user.designated_work_end_time, day.overtime_next_day) %> 
                            <% end %>
                          </td>
                          <td><%= day.work_description %></td>
                          <td><%= a.select :request_overtime_status, [:なし, :申請中, :承認, :否認] %></td>
                          <td><%= a.check_box :overtime_check %></td>
                          <td><%= link_to "確認", show_verify_user_path(user, date: day.worked_on.beginning_of_month),class: "btn btn-primary" %></td>
                        </tr>
                      <% end %>
                    <% end %>  
                  </tbody>
                </table>
                <div class = "center">
                  <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block" %>
                </div>
            <% end %>
          <% end %>  
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/confirmation.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class = "table table-bordered table-condensed user-table">
    <tr>
      <td>
        <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
        <%= l(@first_day, format: :middle) %>時間管理表
        <%= link_to "→", user_path(date: @first_day.next_month),class: "btn btn-primary" %>
      </td>
      <td>
        指定勤務開始時間&nbsp;&nbsp;<%= format_basic_info(@user.designated_work_start_time) %><br>
        指定勤務終了時間<%= format_basic_info(@user.designated_work_end_time) %>
      </td>
      <td colspan = "3">基本時間<%= format_basic_info(@user.basic_work_time) %></td>
      <td>初日&nbsp;&nbsp;<%= l(@first_day, format: :short) %></td>
    </tr>
    
    <tr>
      <td>所属&nbsp;<%= @user.affiliation.present? ? @user.affiliation: "未所属" %></td>
      <td>氏名&nbsp;&nbsp;<%= @user.name %></td>
      <td>コード</td> 
      <td><%=@user.employee_number %></td>
      <td>出勤日数&nbsp;&nbsp;<%= @worked_sum %>日</td>
      <td>締め <%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<div class = "superior-link">
  <% if @user.superior && current_user %>
    <% if @one_month_sum > 0 %>
      <%= link_to "【所属長承認申請のお知らせ】", edit_one_month_approval_user_attendance_path(@user), remote: true, class: "superior__btn" %><sapn style= "border: sold 2px red; color: red;">
      <%= link_to "#{@one_month_sum}件の通知があります" %><br>
    <% else %>
      <%= "【所属長承認申請のお知らせ】" %><br>
    <% end %>
    <% if @change_sum > 0 %>
      <%= link_to "【勤怠変更申請のお知らせ】", edit_request_change_user_attendance_path(@user), remote: true, class:"superior__btn" %>
      <sapn style= "border: solid 2px red; color: red;">
      <%= link_to "#{@change_sum}件の通知があります", edit_request_change_user_attendance_path(@user), remote: true, class:"btn-superior" %></sapn><br>
    <% else %>
      <%= "【勤怠変更申請のお知らせ】" %><br>
    <% end %>
    <% if @overtime_sum > 0 %>
      <%= link_to "【残業申請のお知らせ】", edit_request_overtime_user_attendance_path(@user), remote: true, class: "superior__btn" %>
      <sapn style= "border: sold 2px red; color: red;">
      <%= link_to "#{@overtime_sum}件の通知があります。", edit_overtime_approval_user_attendance_path(@user), remote: true, class: "superior_btn" %></span><br>
    <% else %>
        <%= "【残業申請のお知らせ】" %><br>
    <% end %>
  <% end %>
</div>

<div class="btn-attendance">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>&nbsp;&nbsp;
  <%= link_to "CSV出力", import_user_path(format: :csv), class: "btn btn-primary" %>&nbsp;&nbsp;
  <%= link_to "勤怠修正ログ（承認済）", edit_fix_log_user_attendance_path(@user), class: "btn btn-primary" %>
</div>

<div>
  <table class = "table table-bordered table-condensed table-striped" id = "table-attendances">
    <thead>
      <tr>
        <th rowspan = "3", width = 50>残業申請</th>
        <th rowspan = "3", width = 20>日付</th>
        <th rowspan = "3">曜日</th>
        <th colspan = "7", width = 100>【実績】</th>
        <th colspan = "6", width = 100>所定外勤務</th>
      </tr>
      <tr>
        <th rowspan = "2", width = 20></th>
        <th colspan = "2">出社</th>
        <th colspan = "2">退社</th>
        <th rowspan = "2", width = 50>在社時間</th>
        <th rowspan = "2", width = 100>備考</th>
        <th colspan = "2", width = 10>終了予定時間</th>
        <th rowspan = "2", width = 50>時間外時間</th>
        <th rowspan = "2">業務処理内容</th>
        <th rowspan = "2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><%= link_to "残業申請", edit_request_overtime_user_attendance_path(@user, day), remote: true, class: "btn btn-primary" %></td>                                                                       
          <td><%= l(day.worked_on, format: :short) %></td>              <!--さまざまな処理を並列に行える通信(ajax)に出来る-->
          <td class='<%= "wday#{day.worked_on.wday}" %>'><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td width = 100>
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td><%= l(day.started_at, format: :hour) if day.started_at? %></td>
          <td><%= l(day.started_at, format: :minute) if day.started_at? %></td><!--minuteをja.yml/ formats:にminute: "%M"を追加で解決-->
          <td><%= l(day.finished_at, format: :hour) if day.finished_at? %></td>
          <td><%= l(day.finished_at, format: :minute) if day.finished_at? %></td>
          
          <td>
            <% if day.started_at.present? && day.finished_at? %>
              <%= str_times = working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%= l(day.scheduled_end_time, format: :hour) if day.scheduled_end_time? %></td>
          <td><%= l(day.scheduled_end_time, format: :minute) if day.scheduled_end_time? %></td>
          <td>
            <% if day.scheduled_end_time.present? %><!--時間外時間を計算-->
              <%= working_overtimes(@user.desingnated_worked_end_time, day.next_day) %>
            <% end %>
          </td>
          <td><%= day.work_description %></td>
          <td>
            <% if day.request_overtime_status == "申請中" %>
              <%= "#{day.request_overtime_superior}へ残業#{day.request_overtime_status}" %>
            <% elsif %>
              <% day.request_overtime_status == "承認" || day.request_overtime_status == "否認" %>
                <%= "#{day.request_overtime_superior}より残業#{day.request_overtime_status}" %>      
            <% end %>
            <% if day.request_change_status == "申請中" %>
              <%= "#{day.request_change_superior}へ勤怠変更#{day.request_change_status}" %>
            <% elsif %>
              <% day.request_change_status == "承認" || day.request_change_status == "否認" %>
                <%= "#{day.request_change_superior}より勤怠変更#{day.request_change_status}" %>
            <% end %>
          </td>  
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <!--rowspan:縦結合、colspan:横結合-->
      <tr>
        <td></td>
        <td colspan = "2">累計日数</td>
        <td colspan = "5">総合勤務時間</td>
        <td colspan = "2">累計在社時間</td>
        <td colspan = "3" rowspan = "2"></td>
        <td colspan = "2" rowspan = "2">
          <label>所属長承認 未</label><br>
            <select class="d-grid gap-2 col-3 mx-auto">
              <button type="button" class= "btn btn-outline-dark btn-block" id= "select">Dark<span "caret"></span>
                <option >選択して下さい</option>
                <option ><%= link_to "上長A", "#" %></option>
                <option ><%= link_to "上長B", "#" %></option>
              </button>
            </select>
            
          <button type="button" class="btn btn-primary btn-block">申請</button>
        </td>
      </tr>
      <tr>
        <td></td>
        <td colspan = "2"><%= @attendances.count %></td>
        <td colspan = "5"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan = "2"><%= format("%.2f", @total_working_times.to_f) %></td>
      </tr>
    </tfoot>
  </table>
</div>

<!--モーダルウインドウ表示-->
<div id= "edit-request-overtime" class= "modal fade" tabindex= "-1" role= "dialog" aria-hidden= "true"></div>
<div id= "edit-overtime-approval" class= "modal fade" tabindex= "-1" role= "dialog" aria-hidden= "true"></div>
<div id= "edit-one-month-approval" class= "modal fade" tabindex= "-1" role= "dialog" aria-hidden= "true"></div>
<div id= "edit-request-change" class= "modal fade" tabindex= "-1" role= "dialog" aria-hidden= "true"></div>

app/views/attendances/edit_one_month_approval.js.erb
$("#edit-one-month-approval").html("<%= escape_javascript(render 'edit_one_month_approval') %>");
$("#edit-one-month-approval").modal("show");